### PR TITLE
updated commit

### PR DESCRIPTION
**Pull request by duffysueellen**
updating language

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Need freeze file since you made the edit

**Review by SidharthSaluja — COMMENTED** [review]
Umm nope something seems weird. I should get freeze/posts/___ that sort of file. 

Just hit render on the .qmd

**Comment by duffysueellen** [comment]
All I did was change a few words in descriptions.

**Comment by duffysueellen** [comment]
there are no freeze files

**Review by SidharthSaluja — COMMENTED** [review]
I know you didnt submit freeze thats why  I was asking for it lol

**Review by SidharthSaluja — APPROVED** [review]
Good job

**Pull request merged**
